spring:
#  thymeleaf配置
  thymeleaf:
#    关闭缓存
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc_data
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      #      连接池名
      pool-name: DataHikariCP
      # 最小连接数
      minimum-idle: 5
      # 空闲使劲啊存活最大时间：默认十分钟600000(10分钟)
      idle-timeout: 180000
      # 最大连接数 默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true

