package com.atguigu.mybatis;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.id
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.name
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.gender
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.email
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.d_id
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.id
     *
     * @return the value of tb_employee.id
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.id
     *
     * @param id the value for tb_employee.id
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.name
     *
     * @return the value of tb_employee.name
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.name
     *
     * @param name the value for tb_employee.name
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.gender
     *
     * @return the value of tb_employee.gender
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.gender
     *
     * @param gender the value for tb_employee.gender
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.email
     *
     * @return the value of tb_employee.email
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.email
     *
     * @param email the value for tb_employee.email
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.d_id
     *
     * @return the value of tb_employee.d_id
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public Integer getdId() {
        return dId;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.d_id
     *
     * @param dId the value for tb_employee.d_id
     *
     * @mbggenerated Thu Sep 09 22:56:51 CST 2021
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", gender='" + gender + '\'' +
                ", email='" + email + '\'' +
                ", dId=" + dId +
                '}';
    }

}