person:
#   单引号会将 \n 作为字符串输出 双引号会将 \n 作为换行输出
#   双引号不会转义，单引号会转义
  boss: true
  birth: 2020/10/29
  age: 18
#  interests: [篮球,足球]
  interests:
    - 篮球
    - 足球
    - 18
  animal: [阿猫，阿狗]
#  score:
#    english: 80
#    math: 90

  score: {english:80,math:90}
  salarys:
    - 999.9
    - 999.98
  pet:
    name: 阿狗
    weight: 99.99

  allPets:
    silk:
      - {name: 阿狗, weight: 99.99}
      - name: 阿猫
        weight: 88.88
      - name: 阿虫
        weight: 77.77
    health:
      - {name: 阿花, weight: 199.99 }
      - {name: 阿黄, weight: 10.00}
  user-name: zhangsan


#给静态资源加上前缀进行访问
spring:
  mvc:
    contentnegotiation:
      favor-parameter: true  #开启请求参数内容协商模式，即可以根据 format=xml或json来决定响应浏览器数据的类型

#    mvc:
#      static-path-pattern: /res/**

#把静态资源都放在haha文件下
#    resources:
#      static-locations: [classpath:/haha/]

#server:
#  servlet:
#    context-path: /world
